### ISSUE TITLE
Signing transaction

### ISSUE THREAD

**Issue by taras1vovchenko** [solana-mobile/web3-core#13]
Greetings! I've tried to use your library for parsing and signing transaction from Jupiter. I parsed Message object from transaction, but I have no idea how to set signatures in Transaction using mnemonic (the same as sign transaction, as I understood). Could you, please, provide more complex example?

**Comment by Funkatronics** [comment]
Hi @taras1vovchenko. 

this library does not deal with mnemonics, you'll need to use another library for that. there is a great list of kmp crypto libraries [here](https://github.com/terrakok/kmp-awesome?tab=readme-ov-file#-crypto). Once you parse the mnemonic into a keypair, you can use the methods in this library to sign transactions using the private key.
