### ISSUE TITLE
jvmToolchain version feels a bit legacy?

### ISSUE THREAD

**Issue by etodanik** [solana-mobile/web3-core#3]
Are there good practical reasons for `jvmToolchain` setting in `core` and `solana` packages to be set to 11? It feels like a very old JDK version. Current LTS is v21. I could see v17 being a useful setting for a little while, but 11 feels way legacy.

Is there any practical reason I'm missing?

**Comment by Funkatronics** [comment]
Yes, version 11 is the most compatible from our testing and we will be sticking with it for now.

**Comment by etodanik** [comment]
There are a few environments where this version will already break things very badly.

e.g Unreal from 5.3 *requires* JDK 17.

AGDE debugger (game specific android debugging tool) minimum is 17 starting from Android Studio Flamingo (min. Supported) and onwards. So I imagine Unity will rather quickly move to a more evergreen JDK/SDK policy (especially with anything under 31 not being eligible for updates anymore)

I can see how it's useful to support 11, though. So maybe it'd be a good heads up for devs to explicitly mention that in the getting started (before things break). And let the devs (who most likely are quite aware of what it entails) come prepared.

**Comment by Funkatronics** [comment]
you can still use Java 17. we are only targeting 11 for source combability, as this is currently required to get all android consumers working.

**Comment by Funkatronics** [comment]
so just compile with JDK 17 if that's what you need.
